### ISSUE TITLE
Add url decoding to dsn parts

### ISSUE THREAD

**Issue by josegonzalez** [AD7six/php-dsn#10]
It is sometimes helpful to represent special characters in the host. For example, there is currently no way to specify an email host of `ssl://mail.google.com`.

The hack would be to encode the `://` bit before inclusion:

```
smtp://user:secret@ssl%3A%2F%2Fmail.google.com:25/?from=you@localhost&messageId=1&template=0&layout=0&timeout=30
```

**Comment by ojtibi** [comment]
@josegonzalez IMHO, not only in the host. For example, a password may include characters like [:/-@.?=&] and anything else. Other parts of the DSN may also need URL decoding.

**Comment by ollietreend** [comment]
:thumbsup: +1 for this.

I can't use php-dsn for my email config until "ssl://" in host is supported.

**Comment by josegonzalez** [comment]
Does anyone want to take a stab at this in a pr?

**Comment by ollietreend** [comment]
@josegonzalez Taken a stab at it. I initially toyed with decoding all parameters whose value passed an `is_string()` check. This worked, however things got messy when re-encoding in `toUrlArray()` since it was encoding chars that we didn't necessarily decode - e.g. slashes in path.

I settled for encoding/decoding host, user and pass. Added new tests and all are passing.

Feedback welcome.
