### ISSUE TITLE
How do I specify CakePHP datasource in my DSN?

### ISSUE THREAD

**Issue by davidyell** [AD7six/php-dsn#14]
I'm using the FoC/app-template which implements this plugin and I can't see how to define my datasource.

I'm also struggling to know how to define matching cache configurations.

**Comment by AD7six** [comment]
Are you using a 3.x app?

**Comment by AD7six** [comment]
Well, app-template is 2.x only, so guess not.

There's a couple of ways, the most robust is to [use the map function](https://github.com/AD7six/php-dsn/blob/master/tests/TestCase/Wrapper/CakePHP/V2/DbDsnTest.php#L68):

    Dsn::map('foo', 'UseThisAdapter');
    $dsn = Dsn::parse('foo://....');
    $dsn->datasource === 'UseThisAdapter'

You can also use the `scheme+adapter` syntax:

    $dsn = Dsn::parse('mysql+Fooby.DoobyDriver://...');
    $dsn->datasource === 'Fooby.DoobyDriver'

You can see the existing db adapter map here: https://github.com/AD7six/php-dsn/blob/master/src/Wrapper/CakePHP/V2/DbDsn.php#L19

All dsn wrapper classes work the same, though [the array format is type-specific](https://github.com/AD7six/php-dsn/blob/master/tests/TestCase/Wrapper/CakePHP/V2/CacheDsnTest.php#L59) so that CakePHP understands it.

I'm not sure what "matching cache configurations" means - can you clarify?

**Comment by davidyell** [comment]
I'd like to create, for example, a file cache configuration for 15 minutes and a Redis cache for 1 hour.

**Comment by AD7six** [comment]
You could construct a dsn of the sort:

    api+ApiDatasource.ExampleAPISource://api_user@1234567890:example.com/api/v1?cacheRequests=0

And write your own dsn class for it - but that's not super easy so personally I wouldn't do that.

I assume it's highly unlikely (unlike a framework database connection) that the datasource is a variable for that. So instead you could either use a generic dsn:

    api_dsn=http://api_user:1234567890@example.com/api/v1?cacheRequests=0

    $array = \AD7six\Dsn\Dsn::parse($_ENV['api_dsn'])->toArray();
    Array
    (
        [scheme] => http
        [host] => example.com
        [user] => api_user
        [pass] => 1234567890
        [path] => /api/v1
        [cacheRequests] => 0
    )

And [read that in your database class](https://github.com/FriendsOfCake/app-template/blob/master/app/Config/database.php#L13):

    function __construct() {
        ...
        $api = \AD7six\Dsn\Dsn::parse($_ENV['api_dsn'])->toArray();
        $this->api = [
            'url' => $api['scheme'] . ://' $api['host'] . $api['path'],
            'datasource' => 'ApiDatasource.ExampleAPISource',
            'username' => $api['user'],
            'key' => $api['pass'],
            'cacheRequests' => (bool)$api['cacheRequests']
        ];
    }

OR by whatever means you wish set `$this->api` in the database class.

OR bail on the whole thing and [do it old school](https://github.com/FriendsOfCake/app-template#yeah-thats-not-for-me).

Your described cache configs are [similar to the examples in the test cases](https://github.com/AD7six/php-dsn/blob/master/tests/TestCase/Wrapper/CakePHP/V2/CacheDsnTest.php):

    file:///CACHE/?duration=%2b15%20mins
    redis://localhost/?duration=%2b1%20hour

Out of curiosity, are you starting a new project with app-template _now_? Note that for Cake 3 this repo is obsolete since it [has dsn support out of the box](http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration).

    ConnectionManager::config('default', [
        'url' => 'mysql://my_app:sekret@localhost/my_app?encoding=utf8&timezone=UTC&cacheMetadata=true',
    ]);

[Here's an example of how dsns are normally used](https://github.com/cakephp/cakephp/blob/3.0/.travis.yml#L11-L13).

**Comment by davidyell** [comment]
Yeah, I am creating a project for work and have a whole bunch of plugins which interact with our api so rather than rebuild them all right now, I just want to get the project up and running.

Thanks for the verbose in-depth reply. I'll take a look at this tomorrow morning and see if I can get it implemented.
